/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:910149:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:910149:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:852425:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:852425:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:283395:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield3:283395:

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:856806:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox1:856806:

public void checkbox2_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox2:666692:
  println("checkbox2 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox2:666692:

public void checkbox3_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox3:545766:
  println("checkbox3 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox3:545766:

public void checkbox4_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox4:718822:
  println("checkbox4 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox4:718822:

public void checkbox5_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox5:264324:
  println("checkbox5 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox5:264324:

public void checkbox6_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox6:373425:
  println("checkbox6 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox6:373425:

public void checkbox7_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox7:388812:
  println("checkbox7 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox7:388812:

public void checkbox8_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox8:553317:
  println("checkbox8 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox8:553317:

public void checkbox9_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox9:552271:
  println("checkbox9 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox9:552271:

public void checkbox10_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox10:651947:
  println("checkbox10 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox10:651947:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  label1 = new GLabel(this, 0, 60, 124, 30);
  label1.setText("Beat Sensitivity");
  label1.setTextBold();
  label1.setOpaque(false);
  textfield1 = new GTextField(this, 130, 60, 90, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label2 = new GLabel(this, 0, 110, 124, 30);
  label2.setText("Ball Speed");
  label2.setTextBold();
  label2.setOpaque(false);
  textfield2 = new GTextField(this, 130, 110, 90, 30, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  label3 = new GLabel(this, 0, 160, 124, 30);
  label3.setText("Number of Balls");
  label3.setTextBold();
  label3.setOpaque(false);
  textfield3 = new GTextField(this, 130, 160, 90, 30, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  checkbox1 = new GCheckbox(this, 550, 70, 150, 40);
  checkbox1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox1.setText("  Fill Balls");
  checkbox1.setTextBold();
  checkbox1.setOpaque(false);
  checkbox1.addEventHandler(this, "checkbox1_clicked1");
  label4 = new GLabel(this, 50, 340, 200, 40);
  label4.setText("Background");
  label4.setTextBold();
  label4.setOpaque(false);
  checkbox2 = new GCheckbox(this, 50, 390, 140, 30);
  checkbox2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox2.setText("  No Background");
  checkbox2.setTextBold();
  checkbox2.setOpaque(false);
  checkbox2.addEventHandler(this, "checkbox2_clicked1");
  checkbox2.setSelected(true);
  checkbox3 = new GCheckbox(this, 50, 430, 140, 30);
  checkbox3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox3.setText("  Black");
  checkbox3.setTextBold();
  checkbox3.setOpaque(false);
  checkbox3.addEventHandler(this, "checkbox3_clicked1");
  checkbox4 = new GCheckbox(this, 50, 470, 140, 30);
  checkbox4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox4.setText("  White");
  checkbox4.setTextBold();
  checkbox4.setOpaque(false);
  checkbox4.addEventHandler(this, "checkbox4_clicked1");
  checkbox5 = new GCheckbox(this, 50, 510, 140, 30);
  checkbox5.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox5.setText("  Strobe");
  checkbox5.setTextBold();
  checkbox5.setOpaque(false);
  checkbox5.addEventHandler(this, "checkbox5_clicked1");
  checkbox6 = new GCheckbox(this, 50, 550, 140, 30);
  checkbox6.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox6.setText("  Disco");
  checkbox6.setTextBold();
  checkbox6.setOpaque(false);
  checkbox6.addEventHandler(this, "checkbox6_clicked1");
  label5 = new GLabel(this, 850, 340, 200, 40);
  label5.setText("Effects");
  label5.setTextBold();
  label5.setOpaque(false);
  checkbox7 = new GCheckbox(this, 850, 390, 140, 30);
  checkbox7.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox7.setText("  Balls");
  checkbox7.setTextBold();
  checkbox7.setOpaque(false);
  checkbox7.addEventHandler(this, "checkbox7_clicked1");
  checkbox8 = new GCheckbox(this, 850, 430, 140, 30);
  checkbox8.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox8.setText("  Exploding balls");
  checkbox8.setTextBold();
  checkbox8.setOpaque(false);
  checkbox8.addEventHandler(this, "checkbox8_clicked1");
  checkbox9 = new GCheckbox(this, 850, 470, 140, 30);
  checkbox9.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox9.setText("  Star Streaming");
  checkbox9.setTextBold();
  checkbox9.setOpaque(false);
  checkbox9.addEventHandler(this, "checkbox9_clicked1");
  checkbox10 = new GCheckbox(this, 850, 510, 140, 30);
  checkbox10.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox10.setText("  Rainbow Waveform");
  checkbox10.setTextBold();
  checkbox10.setOpaque(false);
  checkbox10.addEventHandler(this, "checkbox10_clicked1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GTextField textfield1; 
GLabel label2; 
GTextField textfield2; 
GLabel label3; 
GTextField textfield3; 
GCheckbox checkbox1; 
GLabel label4; 
GCheckbox checkbox2; 
GCheckbox checkbox3; 
GCheckbox checkbox4; 
GCheckbox checkbox5; 
GCheckbox checkbox6; 
GLabel label5; 
GCheckbox checkbox7; 
GCheckbox checkbox8; 
GCheckbox checkbox9; 
GCheckbox checkbox10; 

